name: CI

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Export
        run: npm run export
      - name: Fix .nojekyll
        run: touch out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: out
          clean: true
          single-commit: true
